### ISSUE TITLE
Running chips without making 'functions' directory throws an exception

### ISSUE THREAD

**Issue by es-lee** [kinoru/chips#16]
If I run chips without making `~/.config/fish/functions` directory, it throws an exception.

```
$ ./chips

chips: fish plugin manager
version 1.0.0
Build result saved at /home/simnalamburt/.config/chips/build.fish
chips: /home/iioopp90/.config/fish/functions: copyFile: does not exist (No such file or directory)
```

Similar issue with #11

**Comment by xtendo-org** [comment]
Thanks for a report! I'll work on this soon.

**Comment by simnalamburt** [comment]
Looks like this issue have already been fixed in master branch

**Comment by xtendo-org** [comment]
Indeed, this bug has already been fixed in the master branch. (6621994cacd78ae2b31e1ba6712b257fedb36648)

So there are three different approaches:
- Create `~/.config/fish/functions` manually
- Build from source
- Wait for the next release

Sorry for the inconvenience! I'll try to make the next release as soon as possible.
