### ISSUE TITLE
Chips cannot auto-upgrade inself

### ISSUE THREAD

**Issue by simnalamburt** [kinoru/chips#24]
### How to reproduce this error

![image](https://cloud.githubusercontent.com/assets/4435445/19800656/94475b3a-9d36-11e6-8f92-685fa4f42c94.png)

In some reason, uploaded chips **1.1.0** says that its version is **1.0.0**. This might be a clue to fix this bug.

```
chips: fish plugin manager
version 1.0.0
```
### Related issue
- https://github.com/xtendo-org/chips/issues/23

**Comment by xtendo-org** [comment]
The last line says `{"error":"Not Found"}` because of my own confusion when releasing 1.1.0. The executable name should be `chips_gnulinux` for the GNU/Linux (x64) version. I fixed the release file name and the instruction in `README.md`.

Thanks for the report! (and sorry for the inconvenience you had.)
