### ISSUE TITLE
Chips executed with the `--version` argument turns off the fish shell

### ISSUE THREAD

**Issue by simnalamburt** [kinoru/chips#26]
When chips is executed with the `--version` argument, it turns off the parent fish shell.

**Comment by xtendo-org** [comment]
Thank you very much for the report.

I've looked into this and found that any argument at all, not only `--version`, will cause this problem. This is because of the current alias definition we add in `~/.config/chips/build.fish`:

``` fish
alias chips "/home/<username>/.local/bin/chips; exec fish"
```

Therefore `chips --version` becomes `...; exec fish --version`, and since `fish --version` will print the fish version and exit immediately, replacing the current shell with `exec` is equivalent to exiting the shell immediately.

**Comment by simnalamburt** [comment]
Solved by using function instead of alias

**Comment by xtendo-org** [comment]
Solved by 7445a38.
