### ISSUE TITLE
chips shell autocompletion

### ISSUE THREAD

**Issue by encodedfox** [kinoru/chips#9]
Would this lib be useful in getting autocompletion of commands?

The example for this being typing `chips` and then hitting `[TAB]` would then give a prompt out to the shell for the commands available.  This would in theory also allow if you type `chips l` to autocomplete to `chips list` or to give the possible commands from the query.

https://github.com/mbrubeck/compleat

Just found this project and looks awesome.  Great that this is a binary distribution.

**Comment by xtendo-org** [comment]
Thank you.

Well, if I understood correctly, "autocompletion" is useful for autocompleting subcommands and command line options, isn't it?

chips doesn't have any subcommand or command line options.

:open_mouth: what?!

This is a design philosophy; instead of _imperative_ commands like `chips install` or `chips remove` or `chips update`, chips keeps a _declarative_ configuration file that describes the desired state. The `chips` command then tries to sync the system to the described state, like which plugin is installed and which isn't.

By the way, "compleat" looks pretty cool. I guess it's written in Haskell too? Awesome.

**Comment by bucaran** [comment]
I can get that chips won't using completions for what plugins you can download, as there is no universal source for plugins (unless you keep an index like [fisherman](https://github.com/fisherman/fisherman)), but lacking completion for its own commands as well as plugins installed at least once it's either laziness or not really understanding how fish works.

@jmelfi If you like chips minimalist approach, I suggest you take a look at [fin](https://github.com/fishery/fin/), it certainly has completions for its own command and for plugins which you have already installed and can update / uninstall.

**Comment by bucaran** [comment]
Since there is no universal source for plugins, I can understand part of this decision, but lacking completion for even chip's own commands it's just laziness or not really understanding how fish works.

@jmelfi If you like chips minimalist approach, which I do, I suggest you take a look at [fin](https://github.com/fishery/fin/), it has completions for its own commands and for plugins you have already installed and can update or remove, plus a lot of other essential features<sup>§</sup> that render chips useless _unless_ you are only interested in the 2 plugins featured in the README.

<sub>§: support for complex plugin trees, dependencies, functions / completions directories, support for `conf.d` snippets as well as omf init scripts, etc.</sub>

**Comment by simnalamburt** [comment]
@bucaran Let me help you out.

> but lacking completions for even chip's own commands it's just laziness or not really understanding how fish works.

"chips doesn't have any subcommand or command line options." means, there is no subcommand to autocomplete. Are you hoping to provoke a fight with @kinoru or not really understanding how command line works?

Issue tracker is not appropriate place to either advertise your own work or derogate other people's work. Further spamming will be reported as abuse. Thanks.

**Comment by encodedfox** [comment]
@kinoru thank you for the details on that.  

> since `chips` is a utility to keep the plugins in sync it then doesn't need subcommands due to the **declarative** nature.

It's simpler to need to just integrate autocompletion in the plugin for fish shell and let `chips` maintain the desired state.  This cleared up how this tool is structured and intended for use.  This is a really awesome tool and love the binary setup and distribution.  Thanks for publishing this.
